import { RouteConfig } from '../config/snaproute.config';

export interface RouteDoc {
  path: string;
  methods: string[];
  description?: string;
  params?: Record<string, string>;
  generatedAt: string;
}

export function generateDocs(routes: RouteConfig[]): RouteDoc[] {
  return routes.map((route) => ({
    path: route.path,
    methods: route.methods ?? ['GET'],
    description: route.description ?? `Handler for ${route.path}`,
    params: extractParams(route.path),
    generatedAt: new Date().toISOString(),
  }));
}

export function extractParams(routePath: string): Record<string, string> {
  const paramRegex = /\[([^\]]+)\]/g;
  const params: Record<string, string> = {};
  let match: RegExpExecArray | null;

  while ((match = paramRegex.exec(routePath)) !== null) {
    const paramName = match[1];
    params[paramName] = 'string';
  }

  return params;
}

export function formatDocsAsMarkdown(docs: RouteDoc[]): string {
  const lines: string[] = [
    '# API Routes Documentation',
    '',
    `> Auto-generated by snaproute on ${new Date().toLocaleDateString()}`,
    '',
  ];

  for (const doc of docs) {
    lines.push(`## \`${doc.path}\``);
    lines.push('');
    lines.push(`**Methods:** ${doc.methods.map((m) => `\`${m}\``).join(', ')}`);
    lines.push('');
    if (doc.description) {
      lines.push(`**Description:** ${doc.description}`);
      lines.push('');
    }
    const paramEntries = Object.entries(doc.params ?? {});
    if (paramEntries.length > 0) {
      lines.push('**Path Parameters:**');
      lines.push('');
      for (const [key, type] of paramEntries) {
        lines.push(`- \`${key}\` — \`${type}\``);
      }
      lines.push('');
    }
    lines.push('---');
    lines.push('');
  }

  return lines.join('\n');
}
