import * as fs from "fs";
import * as path from "path";
import { generateDocs, formatDocsAsMarkdown } from "./generateDocs";
import type { RouteInput } from "../validate/validateRoute";

export interface WriteDocsOptions {
  outputDir: string;
  docsFileName?: string;
  append?: boolean;
}

export function resolveDocsPath(outputDir: string, fileName: string): string {
  return path.join(outputDir, fileName);
}

export function writeDocsFile(
  routes: RouteInput[],
  options: WriteDocsOptions
): string {
  const { outputDir, docsFileName = "API_DOCS.md", append = false } = options;

  if (routes.length === 0) {
    throw new Error("No routes provided to writeDocsFile.");
  }

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const docsPath = resolveDocsPath(outputDir, docsFileName);

  const sections = routes.map((route) => {
    const docs = generateDocs(route);
    return formatDocsAsMarkdown(docs);
  });

  const content = sections.join("\n---\n\n");

  if (append && fs.existsSync(docsPath)) {
    const existing = fs.readFileSync(docsPath, "utf-8");
    const separator = existing.endsWith("\n") ? "" : "\n";
    fs.writeFileSync(docsPath, `${existing}${separator}\n---\n\n${content}`, "utf-8");
  } else {
    const header = `# API Documentation\n\nAuto-generated by snaproute.\n\n---\n\n`;
    fs.writeFileSync(docsPath, `${header}${content}`, "utf-8");
  }

  return docsPath;
}
