import * as fs from "fs";
import * as path from "path";
import { writeDocsFile, resolveDocsPath } from "./writeDocsFile";
import type { RouteInput } from "../validate/validateRoute";

const TEST_OUTPUT_DIR = path.join(__dirname, "__test_docs_output__");

const sampleRoute: RouteInput = {
  routeName: "users",
  methods: ["GET", "POST"],
  outputDir: TEST_OUTPUT_DIR,
};

const anotherRoute: RouteInput = {
  routeName: "posts/[id]",
  methods: ["GET", "DELETE"],
  outputDir: TEST_OUTPUT_DIR,
};

afterEach(() => {
  if (fs.existsSync(TEST_OUTPUT_DIR)) {
    fs.rmSync(TEST_OUTPUT_DIR, { recursive: true, force: true });
  }
});

describe("resolveDocsPath", () => {
  it("joins outputDir and fileName correctly", () => {
    const result = resolveDocsPath("/some/dir", "API_DOCS.md");
    expect(result).toBe("/some/dir/API_DOCS.md");
  });

  it("uses custom file name", () => {
    const result = resolveDocsPath("/out", "docs.md");
    expect(result).toBe("/out/docs.md");
  });
});

describe("writeDocsFile", () => {
  it("creates output directory if it does not exist", () => {
    writeDocsFile([sampleRoute], { outputDir: TEST_OUTPUT_DIR });
    expect(fs.existsSync(TEST_OUTPUT_DIR)).toBe(true);
  });

  it("writes a markdown file with a header", () => {
    const filePath = writeDocsFile([sampleRoute], { outputDir: TEST_OUTPUT_DIR });
    const content = fs.readFileSync(filePath, "utf-8");
    expect(content).toContain("# API Documentation");
    expect(content).toContain("Auto-generated by snaproute");
  });

  it("includes route information in the docs", () => {
    const filePath = writeDocsFile([sampleRoute], { outputDir: TEST_OUTPUT_DIR });
    const content = fs.readFileSync(filePath, "utf-8");
    expect(content).toContain("users");
    expect(content).toContain("GET");
    expect(content).toContain("POST");
  });

  it("writes multiple routes separated by a divider", () => {
    const filePath = writeDocsFile([sampleRoute, anotherRoute], { outputDir: TEST_OUTPUT_DIR });
    const content = fs.readFileSync(filePath, "utf-8");
    expect(content).toContain("users");
    expect(content).toContain("posts");
    expect(content).toContain("---");
  });

  it("appends to an existing file when append is true", () => {
    writeDocsFile([sampleRoute], { outputDir: TEST_OUTPUT_DIR });
    writeDocsFile([anotherRoute], { outputDir: TEST_OUTPUT_DIR, append: true });
    const filePath = resolveDocsPath(TEST_OUTPUT_DIR, "API_DOCS.md");
    const content = fs.readFileSync(filePath, "utf-8");
    expect(content).toContain("users");
    expect(content).toContain("posts");
  });

  it("returns the resolved file path", () => {
    const filePath = writeDocsFile([sampleRoute], { outputDir: TEST_OUTPUT_DIR, docsFileName: "MY_DOCS.md" });
    expect(filePath).toBe(resolveDocsPath(TEST_OUTPUT_DIR, "MY_DOCS.md"));
  });
});
