import type { SnapRouteConfig } from '../config/snaproute.config';

export interface RouteTemplateOptions {
  routeName: string;
  methods: Array<'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'>;
  withTypes: boolean;
  withDocs: boolean;
}

const METHOD_STUBS: Record<string, string> = {
  GET: `async function GET(req: NextRequest) {
  return NextResponse.json({ message: 'OK' }, { status: 200 });
}`,
  POST: `async function POST(req: NextRequest) {
  const body = await req.json();
  return NextResponse.json({ data: body }, { status: 201 });
}`,
  PUT: `async function PUT(req: NextRequest) {
  const body = await req.json();
  return NextResponse.json({ data: body }, { status: 200 });
}`,
  PATCH: `async function PATCH(req: NextRequest) {
  const body = await req.json();
  return NextResponse.json({ data: body }, { status: 200 });
}`,
  DELETE: `async function DELETE(req: NextRequest) {
  return NextResponse.json({ message: 'Deleted' }, { status: 200 });
}`,
};

export function generateRouteTemplate(
  options: RouteTemplateOptions,
  _config?: Partial<SnapRouteConfig>
): string {
  const { routeName, methods, withTypes, withDocs } = options;

  const imports = [
    `import { NextRequest, NextResponse } from 'next/server';`,
    withTypes ? `import type { ApiResponse } from '@/types/api';` : null,
  ]
    .filter(Boolean)
    .join('\n');

  const docComment = withDocs
    ? `/**\n * Route: ${routeName}\n * Methods: ${methods.join(', ')}\n * Generated by snaproute\n */\n`
    : '';

  const handlers = methods
    .map((m) => METHOD_STUBS[m] ?? `// ${m} handler not implemented`)
    .join('\n\n');

  const exports = methods.map((m) => `export { ${m} };`).join('\n');

  return `${imports}\n\n${docComment}${handlers}\n\n${exports}\n`;
}
