import { generateRouteTemplate } from './routeTemplate';

describe('generateRouteTemplate', () => {
  it('generates a basic GET handler', () => {
    const result = generateRouteTemplate({
      routeName: 'users',
      methods: ['GET'],
      withTypes: false,
      withDocs: false,
    });

    expect(result).toContain('async function GET(req: NextRequest)');
    expect(result).toContain('export { GET }');
    expect(result).toContain("import { NextRequest, NextResponse } from 'next/server'");
  });

  it('generates multiple method handlers', () => {
    const result = generateRouteTemplate({
      routeName: 'posts',
      methods: ['GET', 'POST', 'DELETE'],
      withTypes: false,
      withDocs: false,
    });

    expect(result).toContain('async function GET');
    expect(result).toContain('async function POST');
    expect(result).toContain('async function DELETE');
    expect(result).toContain('export { GET }');
    expect(result).toContain('export { POST }');
    expect(result).toContain('export { DELETE }');
  });

  it('includes type import when withTypes is true', () => {
    const result = generateRouteTemplate({
      routeName: 'items',
      methods: ['GET'],
      withTypes: true,
      withDocs: false,
    });

    expect(result).toContain("import type { ApiResponse } from '@/types/api'");
  });

  it('includes JSDoc comment when withDocs is true', () => {
    const result = generateRouteTemplate({
      routeName: 'orders',
      methods: ['POST'],
      withTypes: false,
      withDocs: true,
    });

    expect(result).toContain('* Route: orders');
    expect(result).toContain('* Methods: POST');
    expect(result).toContain('* Generated by snaproute');
  });

  it('does not include type import when withTypes is false', () => {
    const result = generateRouteTemplate({
      routeName: 'items',
      methods: ['GET'],
      withTypes: false,
      withDocs: false,
    });

    expect(result).not.toContain("import type { ApiResponse }");
  });
});
